using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Scroll : MonoBehaviour
{

    // “®‚­‘¬‚³‚ًŒˆ‚ك‚é
    [SerializeField] float speed;

    // ˆع“®گو‚ئˆع“®ƒ|ƒCƒ“ƒg‚ًŒˆ‚ك‚é
    [SerializeField] float endPos; // ‚±‚±‚ـ‚إ
    [SerializeField] float movePos; // ‚±‚±‚©‚ç

    // Update is called once per frame
    void Update()
    {
        transform.Translate(speed, 0, 0);

        // endPos‚ـ‚إ—ˆ‚½‚çmovePos‚ةˆع“®‚³‚¹‚é
        if (transform.position.x > endPos)
        {
            transform.position = new Vector3(movePos, transform.position.y, 0);
        }
    }
}
